"""
Core Data Models for TTA-Solo.

These models define the ontology - the structure of game entities,
events, universes, and relationships.

Models are stored in:
- Dolt: Entities, Events, Universes (the "Truth")
- Neo4j: Relationships, Embeddings (the "Context")
"""

from src.models.ability import (
    Ability,
    AbilitySource,
    ConditionEffect,
    DamageEffect,
    HealingEffect,
    MagicSubtype,
    MartialSubtype,
    MechanismType,
    StatModifierEffect,
    Targeting,
    TargetingType,
    TechSubtype,
    create_martial_technique,
    create_spell,
    create_tech_ability,
)
from src.models.archetype import (
    ARCHETYPE_HP_BONUS,
    FOCUSES_BY_ARCHETYPE,
    PARADIGM_BONUSES,
    Archetype,
    CharacterClass,
    Focus,
    FocusBonus,
    Paradigm,
    calculate_hp_bonus,
    generate_class,
    get_focus_by_name,
    get_focuses_for_archetype,
    get_paradigm_bonuses,
)
from src.models.condition import (
    ActiveEffect,
    ConditionInstance,
    ConditionType,
    DurationType,
    EntityCombatState,
    ModifierType,
    create_active_effect,
    create_combat_state,
    create_condition,
)
from src.models.entity import (
    AbilityScores,
    Entity,
    EntityStats,
    EntityType,
    FactionProperties,
    ItemProperties,
    LocationProperties,
    create_character,
    create_faction,
    create_item,
    create_location,
)
from src.models.event import (
    CheckPayload,
    CombatPayload,
    DialoguePayload,
    Event,
    EventOutcome,
    EventType,
    ForkPayload,
    ItemPayload,
    RestPayload,
    TransactionPayload,
    TravelPayload,
    create_check_event,
    create_combat_event,
    create_dialogue_event,
    create_fork_event,
    create_travel_event,
)
from src.models.npc import (
    MemoryType,
    Motivation,
    NPCMemory,
    NPCProfile,
    PersonalityTraits,
    create_memory,
    create_npc_profile,
)
from src.models.physics_overlay import (
    CYBERPUNK_OVERLAY,
    HIGH_FANTASY_OVERLAY,
    HORROR_OVERLAY,
    LOW_MAGIC_OVERLAY,
    MYTHIC_OVERLAY,
    NEUTRAL_OVERLAY,
    OVERLAY_REGISTRY,
    POST_APOCALYPTIC_OVERLAY,
    ConditionModifier,
    PhysicsOverlay,
    SourceModifier,
    apply_condition_dc_overlay,
    apply_condition_duration_overlay,
    apply_healing_overlay,
    apply_stress_overlay,
    get_overlay,
    get_source_effect,
    list_overlays,
)
from src.models.quest import (
    ObjectiveType,
    Quest,
    QuestObjective,
    QuestReward,
    QuestStatus,
    QuestTemplate,
    QuestType,
    create_objective,
    create_quest,
)
from src.models.relationships import (
    FearsRelationship,
    KnowsRelationship,
    LocatedInRelationship,
    Relationship,
    RelationshipType,
    VariantOfRelationship,
    create_knows_relationship,
    create_located_in,
    create_variant,
)
from src.models.resources import (
    CooldownRechargeResult,
    CooldownTracker,
    EntityResources,
    MomentumChangeResult,
    SpellSlotTracker,
    StressChangeResult,
    StressMomentumPool,
    UsageDie,
    UsageDieResult,
    create_cooldown_tracker,
    create_spell_slots,
    create_usage_die,
)
from src.models.universe import (
    Universe,
    UniverseConnection,
    UniverseStatus,
    create_fork,
    create_prime_material,
    create_shared_adventure,
)

__all__ = [
    # Ability (UAO)
    "Ability",
    "AbilitySource",
    "MagicSubtype",
    "TechSubtype",
    "MartialSubtype",
    "MechanismType",
    "TargetingType",
    "Targeting",
    "DamageEffect",
    "HealingEffect",
    "ConditionEffect",
    "StatModifierEffect",
    "create_spell",
    "create_tech_ability",
    "create_martial_technique",
    # Resources
    "UsageDie",
    "UsageDieResult",
    "CooldownTracker",
    "CooldownRechargeResult",
    "StressMomentumPool",
    "StressChangeResult",
    "MomentumChangeResult",
    "SpellSlotTracker",
    "EntityResources",
    "create_usage_die",
    "create_cooldown_tracker",
    "create_spell_slots",
    # Condition/Combat State
    "ConditionType",
    "DurationType",
    "ModifierType",
    "ConditionInstance",
    "ActiveEffect",
    "EntityCombatState",
    "create_condition",
    "create_active_effect",
    "create_combat_state",
    # Entity
    "Entity",
    "EntityType",
    "EntityStats",
    "AbilityScores",
    "ItemProperties",
    "LocationProperties",
    "FactionProperties",
    "create_character",
    "create_location",
    "create_item",
    "create_faction",
    # NPC
    "PersonalityTraits",
    "Motivation",
    "NPCProfile",
    "MemoryType",
    "NPCMemory",
    "create_npc_profile",
    "create_memory",
    # Event
    "Event",
    "EventType",
    "EventOutcome",
    "CombatPayload",
    "DialoguePayload",
    "TravelPayload",
    "ItemPayload",
    "TransactionPayload",
    "CheckPayload",
    "RestPayload",
    "ForkPayload",
    "create_combat_event",
    "create_dialogue_event",
    "create_travel_event",
    "create_check_event",
    "create_fork_event",
    # Universe
    "Universe",
    "UniverseStatus",
    "UniverseConnection",
    "create_prime_material",
    "create_fork",
    "create_shared_adventure",
    # Relationships
    "Relationship",
    "RelationshipType",
    "KnowsRelationship",
    "LocatedInRelationship",
    "FearsRelationship",
    "VariantOfRelationship",
    "create_knows_relationship",
    "create_located_in",
    "create_variant",
    # Quest
    "Quest",
    "QuestStatus",
    "QuestType",
    "QuestObjective",
    "ObjectiveType",
    "QuestReward",
    "QuestTemplate",
    "create_quest",
    "create_objective",
    # Archetype
    "Archetype",
    "Paradigm",
    "Focus",
    "FocusBonus",
    "CharacterClass",
    "FOCUSES_BY_ARCHETYPE",
    "ARCHETYPE_HP_BONUS",
    "PARADIGM_BONUSES",
    "get_focuses_for_archetype",
    "get_focus_by_name",
    "calculate_hp_bonus",
    "get_paradigm_bonuses",
    "generate_class",
    # Physics Overlay
    "SourceModifier",
    "ConditionModifier",
    "PhysicsOverlay",
    "HIGH_FANTASY_OVERLAY",
    "LOW_MAGIC_OVERLAY",
    "CYBERPUNK_OVERLAY",
    "HORROR_OVERLAY",
    "MYTHIC_OVERLAY",
    "POST_APOCALYPTIC_OVERLAY",
    "NEUTRAL_OVERLAY",
    "OVERLAY_REGISTRY",
    "get_overlay",
    "list_overlays",
    "apply_healing_overlay",
    "apply_stress_overlay",
    "apply_condition_duration_overlay",
    "apply_condition_dc_overlay",
    "get_source_effect",
]
